drop table if exists admin_permission;

create table admin_permission
(
    code        varchar(32) not null primary key,
    parent_code varchar(32),
    menu        smallint    not null,
    path        varchar(80) not null unique,
    name        varchar(40) not null unique,
    memo        varchar(200),
    icon        varchar(200),
    status      smallint     not null,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp
);

insert into
    admin_permission
    (
        code,
        parent_code,
        menu,
        path,
        name,
        icon,
        status
    )
values
    (
        '001_admin_manage',
        null,
        1,
        '/admin',
        '权限管理',
        'menu',
        1
    ),
    (
        '002_admin_user_index',
        '001_admin_manage',
        1,
        '/admin/user',
        '管理员',
        'team',
        1
    ),
    (
        '003_admin_role_index',
        '001_admin_manage',
        1,
        '/admin/role',
        '角色',
        'user',
        1
    ),
    (
        '004_admin_permission_index',
        '001_admin_manage',
        1,
        '/admin/permission',
        '权限',
        'lock',
        1
    ),
    (
        '005_add_admin_user',
        '002_admin_user_index',
        2,
        'POST/admin/user/add',
        '添加管理员',
        '',
        1
    ),
    (
        '006_del_admin_user',
        '002_admin_user_index',
        2,
        'GET/admin/user/del',
        '删除管理员',
        '',
        1
    ),
    (
        '007_edit_admin_user',
        '002_admin_user_index',
        2,
        'PUT/admin/user/del',
        '修改管理员',
        '',
        1
    ),
    (
        '008_find_admin_user',
        '002_admin_user_index',
        2,
        'GET/admin/user/find',
        '查询管理员信息',
        '',
        1
    ),
    (
        '009_query_admin_user',
        '002_admin_user_index',
        2,
        'GET/admin/user/query',
        '查询管理员列表',
        '',
        1
    ),
    (
        '010_add_admin_role',
        '003_admin_role_index',
        2,
        'POST/admin/role/add',
        '添加角色',
        '',
        1
    ),
    (
        '011_del_admin_role',
        '003_admin_role_index',
        2,
        'DELETE/admin/role/del',
        '删除角色',
        '',
        1
    ),
    (
        '012_edit_admin_role',
        '003_admin_role_index',
        2,
        'PUT/admin/role/edit',
        '修改角色',
        '',
        1
    ),
    (
        '013_find_admin_role',
        '003_admin_role_index',
        2,
        'GET/admin/role/find',
        '查询角色信息',
        '',
        1
    ),
    (
        '014_query_admin_role',
        '003_admin_role_index',
        2,
        'GET/admin/role/query',
        '查询角色信息列表',
        '',
        1
    ),
    (
        '015_add_admin_permission',
        '004_admin_permission_index',
        2,
        'POST/admin/permission/add',
        '添加权限',
        '',
        1
    ),
    (
        '016_del_admin_permission',
        '004_admin_permission_index',
        2,
        'DELETE/admin/permission/del',
        '删除权限',
        '',
        1
    ),
    (
        '017_edit_admin_permission',
        '004_admin_permission_index',
        2,
        'PUT/admin/permission/edit',
        '修改权限',
        '',
        1
    ),
    (
        '018_find_admin_permission',
        '004_admin_permission_index',
        2,
        'GET/admin/permission/find',
        '查询权限信息',
        '',
        1
    ),
    (
        '019_query_admin_permission',
        '004_admin_permission_index',
        2,
        'GET/admin/permission/query',
        '查询权限信息列表',
        '',
        1
    ),
    (
        '020_user_attach_role',
        '002_admin_user_index',
        2,
        'POST/admin/attach/user/role',
        '用户附加角色',
        '',
        1
    ),
    (
        '021_user_detach_role',
        '002_admin_user_index',
        2,
        'POST/admin/detach/user/role',
        '用户分离角色',
        '',
        1
    ),
    (
        '022_user_attach_permission',
        '002_admin_user_index',
        2,
        'POST/admin/attach/user/permission',
        '用户附加权限',
        '',
        1
    ),
    (
        '023_user_detach_permission',
        '002_admin_user_index',
        2,
        'POST/admin/detach/user/permission',
        '用户分离权限',
        '',
        1
    ),
    (
        '024_role_attach_permission',
        '003_admin_role_index',
        2,
        'POST/admin/attach/role/permission',
        '角色附加权限',
        '',
        1
    ),
    (
        '025_role_detach_permission',
        '003_admin_role_index',
        2,
        'POST/admin/detach/role/permission',
        '角色分离权限',
        '',
        1
    ),
    (
        '026_permission_struct_tree',
        '003_admin_role_index',
        2,
        'POST/admin/permission/tree',
        '权限结构树',
        '',
        1
    ),
    (
        '027_admin_user_status',
        '002_admin_user_index',
        2,
        'POST/admin/user/status',
        '批量修改用户状态',
        '',
        1
    ),
    (
        '028_admin_role_status',
        '003_admin_role_index',
        2,
        'POST/admin/role/status',
        '批量修改角色状态',
        '',
        1
    ),
    (
        '029_admin_permission_status',
        '004_admin_permission_index',
        2,
        'POST/admin/permission/status',
        '批量修改权限状态',
        '',
        1
    ),
    (
        '030_admin_user_check',
        '002_admin_user_index',
        2,
        'GET/admin/check',
        '用户信息',
        '',
        1
    );